devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max"
])

languages([
  "en-US"
])

scheme "WeatherEE"

clear_previous_screenshots true

workspace "./WeatherEE.xcworkspace"
